package kexpresso

import kotlin.random.Random

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Generates up to [count] distinct strings that match this pattern, by walking its AST.
 *
 * **Supported nodes (guaranteed to produce matching strings):**
 * `SequenceNode`, `Literal`, `Token` (known fixed primitives), `Quantifier`, `Group`
 * (all flavours: non-capturing, capturing, named), and `Alternation`.
 *
 * **Best-effort / unsupported nodes:**
 * - [Raw] — used by [KexpressoBuilder.raw], by every domain/helper extension (`email()`,
 *   `ipv4()`, `isoDate()`, …), and by [Kexpresso.from]. Generation emits an empty string
 *   for the raw fragment; the result may not satisfy [matches].
 * - [Lookaround] — zero-width assertions cannot be synthesised generically; the assertion
 *   is skipped (empty string emitted).
 * - [Backreference] — the referenced captured text is not tracked during generation; an
 *   empty string is emitted for the back-reference position.
 *
 * When the AST contains only supported nodes every returned string satisfies [matches].
 * When any unsupported node is present generation is best-effort and may not match; in that
 * case the result list is still returned (never thrown).
 *
 * @param count maximum number of distinct examples to return. For fully-fixed patterns
 *              (e.g. a bare [literal]) the returned list may be smaller.
 * @param seed  seed for the pseudo-random choices (quantifier lengths, alternation branches);
 *              the same seed always produces the same list.
 * @return a list of distinct strings, each generated by walking the AST with [seed]-derived
 *         random choices.
 */
@ExperimentalKexpressoApi
fun KexpressoPattern.examples(count: Int = 5, seed: Long = 0): List<String> {
    require(count >= 0) { "count must be >= 0, but was $count" }
    if (count == 0) return emptyList()
    val results = LinkedHashSet<String>(count * 2)
    var attempt = 0
    // Try up to count*4 attempts to gather distinct examples (capped to avoid infinite loops
    // for fixed patterns that can only produce one string).
    val maxAttempts = maxOf(count * 4, 16)
    while (results.size < count && attempt < maxAttempts) {
        val rng = Random(seed + attempt)
        results += generateNode(ast, rng)
        attempt++
    }
    return results.toList()
}

// ── Internal generation ───────────────────────────────────────────────────────

/**
 * Recursively generates a string for [node] using [rng] for all random choices.
 */
private fun generateNode(node: RegexNode, rng: Random): String = when (node) {
    is SequenceNode -> node.children.joinToString("") { generateNode(it, rng) }
    is Literal -> node.text
    is Token -> generateToken(node.regex, rng)
    is Quantifier -> generateQuantifier(node, rng)
    is Group -> generateNode(node.child, rng)
    is Alternation -> generateNode(node.branches[rng.nextInt(node.branches.size)], rng)
    // ── Unsupported: emit empty string (best-effort) ─────────────────────────
    is Raw -> ""
    is Lookaround -> ""
    is Backreference -> ""
}

/**
 * Generates a repeat of the quantifier's child the appropriate number of times.
 */
private fun generateQuantifier(node: Quantifier, rng: Random): String {
    val count = repeatCount(node.kind, rng)
    return buildString { repeat(count) { append(generateNode(node.child, rng)) } }
}

private fun repeatCount(kind: QuantifierKind, rng: Random): Int = when (kind) {
    is QuantifierKind.Optional -> rng.nextInt(2)          // 0 or 1
    is QuantifierKind.ZeroOrMore -> rng.nextInt(4)        // 0..3
    is QuantifierKind.OneOrMore -> 1 + rng.nextInt(3)    // 1..3
    is QuantifierKind.Exactly -> kind.n
    is QuantifierKind.AtLeast -> kind.n + rng.nextInt(3)  // n..n+2
    is QuantifierKind.Between -> kind.min + rng.nextInt(kind.max - kind.min + 1) // min..max
}

// ── Token generation ──────────────────────────────────────────────────────────

/** Digits 0-9. */
private val DIGITS = ('0'..'9').toList()

/** ASCII lowercase letters. */
private val LOWER = ('a'..'z').toList()

/** ASCII uppercase letters. */
private val UPPER = ('A'..'Z').toList()

/** ASCII letters (upper + lower). */
private val LETTERS = LOWER + UPPER

/** ASCII letters + digits. */
private val ALPHANUMERICS = LETTERS + DIGITS

/** Characters that are NOT digits (a small safe set of ASCII letters). */
private val NON_DIGIT_CHARS = LETTERS

/** Characters that are NOT word chars (\w = [a-zA-Z0-9_]). */
private val NON_WORD_CHARS = listOf('!', '@', '#', '%', '&', '-', '+', '=', '?', '/')

/** Characters that are NOT whitespace. */
private val NON_WS_CHARS = ALPHANUMERICS

/** Sentence-ending punctuation. */
private val END_PUNCT = listOf('.', '!', '?')

/**
 * Maps a known [Token.regex] string to a generator that produces one matching character/string.
 *
 * Keys are the verbatim regex strings as emitted by the builder.
 */
private val TOKEN_GENERATORS: Map<String, (Random) -> String> = buildMap {
    // Digits / words / whitespace
    put("\\d") { rng -> DIGITS[rng.nextInt(DIGITS.size)].toString() }
    put("\\D") { rng -> NON_DIGIT_CHARS[rng.nextInt(NON_DIGIT_CHARS.size)].toString() }
    put("\\w") { rng -> (ALPHANUMERICS + '_')[rng.nextInt(ALPHANUMERICS.size + 1)].toString() }
    put("\\W") { rng -> NON_WORD_CHARS[rng.nextInt(NON_WORD_CHARS.size)].toString() }
    put("\\s") { _ -> " " }
    put("\\S") { rng -> NON_WS_CHARS[rng.nextInt(NON_WS_CHARS.size)].toString() }
    // Dot
    put(".") { _ -> "x" }
    // Character classes
    put("[a-zA-Z]") { rng -> LETTERS[rng.nextInt(LETTERS.size)].toString() }
    put("[A-Z]") { rng -> UPPER[rng.nextInt(UPPER.size)].toString() }
    put("[a-z]") { rng -> LOWER[rng.nextInt(LOWER.size)].toString() }
    put("[a-zA-Z0-9]") { rng -> ALPHANUMERICS[rng.nextInt(ALPHANUMERICS.size)].toString() }
    put("[.!?]") { rng -> END_PUNCT[rng.nextInt(END_PUNCT.size)].toString() }
    // Control characters
    put("\\t") { _ -> "\t" }
    put("\\n") { _ -> "\n" }
    put("\\r") { _ -> "\r" }
    // Zero-width anchors → empty string (they consume no characters)
    for (anchor in listOf("\\A", "\\z", "^", "\$", "\\b", "\\B")) {
        put(anchor) { _ -> "" }
    }
}

/**
 * Generates a single string satisfying the given [tokenRegex].
 *
 * Known tokens are handled via [TOKEN_GENERATORS]. For unknown `[...]` classes a simple
 * parser extracts ranges and literals and picks one member. Everything else falls back
 * to the safe character `"x"`.
 */
private fun generateToken(tokenRegex: String, rng: Random): String {
    TOKEN_GENERATORS[tokenRegex]?.let { return it(rng) }
    // Best-effort character class, else a safe placeholder.
    return generateCharClassChar(tokenRegex, rng) ?: "x"
}

/**
 * Generates a single character satisfying a `[...]` / `[^...]` character-class token, or `null`
 * if [tokenRegex] is not a character class (or no member can be produced).
 *
 * Negated classes pick a safe character that is NOT excluded, so the generated example still
 * satisfies the class (e.g. `noneOf("x")` must never yield `"x"`).
 */
private fun generateCharClassChar(tokenRegex: String, rng: Random): String? {
    if (!tokenRegex.startsWith('[') || !tokenRegex.endsWith(']')) return null
    val inner = tokenRegex.substring(1, tokenRegex.length - 1)
    return if (inner.startsWith('^')) {
        val excluded = parseClassMembers(inner.substring(1)).toSet()
        (ALPHANUMERICS + ' ' + NON_WORD_CHARS).firstOrNull { it !in excluded }?.toString()
    } else {
        val members = parseClassMembers(inner)
        if (members.isEmpty()) null else members[rng.nextInt(members.size)].toString()
    }
}

/**
 * Parses the body of a character class — the part between `[` and `]`, with any leading `^`
 * already removed — like `abc`, `a-z`, or `a-zA-Z0-9`, into the characters it represents.
 *
 * Handles ranges (`a-z`), escapes (`\d`, `\w`, `\s`), and individual characters.
 */
private fun parseClassMembers(inner: String): List<Char> {
    val result = mutableListOf<Char>()
    var i = 0
    while (i < inner.length) {
        val c = inner[i]
        if (c == '\\' && i + 1 < inner.length) {
            // Escaped char inside the class
            val next = inner[i + 1]
            when (next) {
                'd' -> result.addAll(DIGITS)
                'w' -> result.addAll(ALPHANUMERICS + '_')
                's' -> result.add(' ')
                else -> result.add(next)
            }
            i += 2
        } else if (i + 2 < inner.length && inner[i + 1] == '-') {
            // Range a-z
            val from = c
            val to = inner[i + 2]
            for (code in from.code..to.code) result.add(code.toChar())
            i += 3
        } else {
            result.add(c)
            i++
        }
    }
    return result
}
